import AuthProvider from './auth-provider'
import './globals.css'
import NavMenu from './nav-menu'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AuthProvider>
      <html lang='en'>
        <body>
          {/* @ts-expect-error Server Component */}
          <NavMenu />
          {children}
        </body>
      </html>
    </AuthProvider>
  )
}
